In [85]:
import pandas as pd

In [86]:
drivers = pd.read_csv("/Users/alexa/Projects/ssp_libya/ssp_modeling/tableau/data/drivers_libya.csv")

/var/folders/3p/n363h71s3gg0h1brsrv7f_zr0000gn/T/ipykernel_46485/982225212.py:1: DtypeWarning: Columns (10,20) have mixed types. Specify dtype option on import or set low_memory=False.
  drivers = pd.read_csv("/Users/alexa/Projects/ssp_libya/ssp_modeling/tableau/data/drivers_libya.csv")

In [87]:
drivers = drivers[
    (drivers['variable'] == "gdp_mmm_usd")
    & (drivers['primary_id'] != 0)
    & (drivers['strategy'] != "Historical")
    #& (drivers['strategy'] != "Strategy TX:BASE")
][['Year', 'strategy', 'strategy_id', 'value']]

drivers = drivers.rename(columns={'value': 'gdp'})

In [88]:
emissions = pd.read_csv("/Users/alexa/Projects/ssp_libya/ssp_modeling/tableau/data/decomposed_emissions_libya_2023.csv")
emissions = emissions.groupby(['Year','strategy']).agg({'value': 'sum'}).reset_index()
emissions = emissions[
    #(emissions['strategy'] != "Strategy TX:BASE")
     (emissions['strategy'] != "Historical")
]
emissions.rename(columns={'value': 'emissions'}, inplace=True)

In [89]:
intensity = pd.merge(emissions, drivers, on=['Year','strategy'], how='left')

intensity['intensity'] = intensity['emissions'] / (intensity['gdp']/3)
intensity

     Year          strategy   emissions  strategy_id         gdp  intensity
0    2023               BAU   96.671032       6003.0  101.162039   2.866817
1    2023       Conditional   96.671032       6005.0  101.162039   2.866817
2    2023  Strategy TX:BASE   96.671032          NaN         NaN        NaN
3    2023     Unconditional   96.671032       6004.0  101.162039   2.866817
4    2024               BAU   94.157192       6003.0  105.576742   2.675510
..    ...               ...         ...          ...         ...        ...
107  2049     Unconditional   71.073317       6004.0  173.209835   1.230992
108  2050               BAU  111.989709       6003.0  176.674032   1.901633
109  2050       Conditional   39.899284       6005.0  176.674032   0.677507
110  2050  Strategy TX:BASE  113.176518          NaN         NaN        NaN
111  2050     Unconditional   69.544836       6004.0  176.674032   1.180901

[112 rows x 6 columns]

In [90]:
intensity.to_csv("/Users/alexa/Projects/ssp_libya/ssp_modeling/tableau/data/emissions_intensity.csv", index=False)

# Check new input data values

In [6]:
input_data = pd.read_csv("/Users/alexa/Projects/ssp_libya/ssp_modeling/input_data/df_input_0.csv")
input_data

,year,ef_ippu_tonne_nf3_per_tonne_production_chemicals,ef_ippu_tonne_nf3_per_tonne_production_electronics,ef_ippu_tonne_sf6_per_mmm_gdp_other_product_manufacturing,ef_ippu_tonne_sf6_per_tonne_production_chemicals,ef_ippu_tonne_sf6_per_tonne_production_electronics,ef_ippu_tonne_sf6_per_tonne_production_metals,frac_agrc_bevs_and_spices_cl2_dry,frac_agrc_cereals_cl2_dry,frac_agrc_fibers_cl2_dry,...,ef_fgtv_transmission_tonne_ch4_per_m3_fuel_crude,ef_fgtv_transmission_tonne_co2_per_m3_fuel_crude,ef_fgtv_transmission_tonne_n2o_per_m3_fuel_crude,ef_fgtv_distribution_tonne_ch4_per_m3_fuel_crude,ef_fgtv_distribution_tonne_co2_per_m3_fuel_crude,ef_fgtv_production_fugitive_tonne_nmvoc_per_m3_fuel_crude,ef_fgtv_production_venting_tonne_nmvoc_per_m3_fuel_crude,ef_fgtv_production_flaring_tonne_nmvoc_per_m3_fuel_crude,ef_fgtv_transmission_tonne_nmvoc_per_m3_fuel_crude,frac_fgtv_drained_and_waste_ch4_flared_fuel_crude
0,2015,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,...,0.000015,0.000001,0.0,0.0,0.0,0.014,0.00188,0.00625,0.000152,0.087
1,2016,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,...,0.000015,0.000001,0.0,0.0,0.0,0.014,0.00188,0.00625,0.000152,0.087
2,2017,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,...,0.000015,0.000001,0.0,0.0,0.0,0.014,0.00188,0.00625,0.000152,0.087
3,2018,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,...,0.000015,0.000001,0.0,0.0,0.0,0.014,0.00188,0.00625,0.000152,0.087
4,2019,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,...,0.000015,0.000001,0.0,0.0,0.0,0.014,0.00188,0.00625,0.000152,0.087
5,2020,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,...,0.000015,0.000001,0.0,0.0,0.0,0.014,0.00188,0.00625,0.000152,0.087
6,2021,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,...,0.000015,0.000001,0.0,0.0,0.0,0.014,0.00188,0.00625,0.000152,0.087
7,2022,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,...,0.000015,0.000001,0.0,0.0,0.0,0.014,0.00188,0.00625,0.000152,0.087
8,2023,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,...,0.000015,0.000001,0.0,0.0,0.0,0.014,0.00188,0.00625,0.000152,0.087
9,2024,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,...,0.000015,0.000001,0.0,0.0,0.0,0.014,0.00188,0.00625,0.000152,0.087
10,2025,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,...,0.000015,0.000001,0.0,0.0,0.0,0.014,0.00188,0.00625,0.000152,0.087
11,2026,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,...,0.000015,0.000001,0.0,0.0,0.0,0.014,0.00188,0.00625,0.000152,0.087
12,2027,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,...,0.000015,0.000001,0.0,0.0,0.0,0.014,0.00188,0.00625,0.000152,0.087
13,2028,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,...,0.000015,0.000001,0.0,0.0,0.0,0.014,0.00188,0.00625,0.000152,0.087
14,2029,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,...,0.000015,0.000001,0.0,0.0,0.0,0.014,0.00188,0.00625,0.000152,0.087
15,2030,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,...,0.000015,0.000001,0.0,0.0,0.0,0.014,0.00188,0.00625,0.000152,0.087
16,2031,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,...,0.000015,0.000001,0.0,0.0,0.0,0.014,0.00188,0.00625,0.000152,0.087
17,2032,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,...,0.000015,0.000001,0.0,0.0,0.0,0.014,0.00188,0.00625,0.000152,0.087
18,2033,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,...,0.000015,0.000001,0.0,0.0,0.0,0.014,0.00188,0.00625,0.000152,0.087
19,2034,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,...,0.000015,0.000001,0.0,0.0,0.0,0.014,0.00188,0.00625,0.000152,0.087
20,2035,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,...,0.000015,0.000001,0.0,0.0,0.0,0.014,0.00188,0.00625,0.000152,0.087
21,2036,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,...,0.000015,0.000001,0.0,0.0,0.0,0.014,0.00188,0.00625,0.000152,0.087
22,2037,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,...,0.000015,0.000001,0.0,0.0,0.0,0.014,0.00188,0.00625,0.000152,0.087
23,2038,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,...,0.000015,0.000001,0.0,0.0,0.0,0.014,0.00188,0.00625,0.000152,0.087
24,2039,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,...,0.000015,0.000001,0.0,0.0,0.0,0.014,0.00188,0.00625,0.000152,0.087
25,2040,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,...,0.000015,0.000001,0.0,0.0,0.0,0.014,0.00188,0.00625,0.000152,0.087
26,2041,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,...,0.000015,0.000001,0.0,0.0,0.0,0.014,0.00188,0.00625,0.000152,0.087
27,2042,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,...,0.000015,0.000001,0.0,0.0,0.0,0.014,0.00188,0.00625,0.000152,0.087
28,2043,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,...,0.000015,0.000001,0.0,0.0,0.0,0.014,0.00188,0.00625,0.000152,0.087
29,2044,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,...,0.000015,0.000001,0.0,0.0,0.0,0.014,0.00188,0.00625,0.000152,0.087
30,2045,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,...,0.000015,0.000001,0.0,0.0,0.0,0.014,0.00188,0.00625,0.000152,0.087
31,2046,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,...,0.000015,0.000001,0.0,0.0,0.0,0.014,0.00188,0.00625,0.000152,0.087
32,2047,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,...,0.000015,0.000001,0.0,0.0,0.0,0.014,0.00188,0.00625,0.000152,0.087
33,2048,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,...,0.000015,0.000001,0.0,0.0,0.0,0.014,0.00188,0.00625,0.000152,0.087
34,2049,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,...,0.000015,0.000001,0.0,0.0,0.0,0.014,0.00188,0.00625,0.000152,0.087
35,2050,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,...,0.000015,0.000001,0.0,0.0,0.0,0.014,0.00188,0.00625,0.000152,0.087
36,2051,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,...,0.000015,0.000001,0.0,0.0,0.0,0.014,0.00188,0.00625,0.000152,0.087
37,2052,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,...,0.000015,0.000001,0.0,0.0,0.0,0.014,0.00188,0.00625,0.000152,0.087
38,2053,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,...,0.000015,0.000001,0.0,0.0,0.0,0.014,0.00188,0.00625,0.000152,0.087
39,2054,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,...,0.000015,0.000001,0.0,0.0,0.0,0.014,0.00188,0.00625,0.000152,0.087
40,2055,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,...,0.000015,0.000001,0.0,0.0,0.0,0.014,0.00188,0.00625,0.000152,0.087
41,2056,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,...,0.000015,0.000001,0.0,0.0,0.0,0.014,0.00188,0.00625,0.000152,0.087
42,2057,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,...,0.000015,0.000001,0.0,0.0,0.0,0.014,0.00188,0.00625,0.000152,0.087
43,2058,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,...,0.000015,0.000001,0.0,0.0,0.0,0.014,0.00188,0.00625,0.000152,0.087
44,2059,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,...,0.000015,0.000001,0.0,0.0,0.0,0.014,0.00188,0.00625,0.000152,0.087
45,2060,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,...,0.000015,0.000001,0.0,0.0,0.0,0.014,0.00188,0.00625,0.000152,0.087
46,2061,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,...,0.000015,0.000001,0.0,0.0,0.0,0.014,0.00188,0.00625,0.000152,0.087
47,2062,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,...,0.000015,0.000001,0.0,0.0,0.0,0.014,0.00188,0.00625,0.000152,0.087
48,2063,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,...,0.000015,0.000001,0.0,0.0,0.0,0.014,0.00188,0.00625,0.000152,0.087
49,2064,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,...,0.000015,0.000001,0.0,0.0,0.0,0.014,0.00188,0.00625,0.000152,0.087
50,2065,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,...,0.000015,0.000001,0.0,0.0,0.0,0.014,0.00188,0.00625,0.000152,0.087
51,2066,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,...,0.000015,0.000001,0.0,0.0,0.0,0.014,0.00188,0.00625,0.000152,0.087
52,2067,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,...,0.000015,0.000001,0.0,0.0,0.0,0.014,0.00188,0.00625,0.000152,0.087
53,2068,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,...,0.000015,0.000001,0.0,0.0,0.0,0.014,0.00188,0.00625,0.000152,0.087
54,2069,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,...,0.000015,0.000001,0.0,0.0,0.0,0.014,0.00188,0.00625,0.000152,0.087
55,2070,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,...,0.000015,0.000001,0.0,0.0,0.0,0.014,0.00188,0.00625,0.000152,0.087

In [7]:
last_input_data = pd.read_csv("/Users/alexa/Projects/ssp_libya/ssp_modeling/input_data/sisepuede_raw_inputs_latest_LBY_modified_march_2026.csv")

In [ ]:
last_input_data.columns
input_data.columns

In [8]:
# Columns present in one DataFrame but not the other
only_in_last = last_input_data.columns.difference(input_data.columns)
only_in_input = input_data.columns.difference(last_input_data.columns)
print("Only in last_input_data:")
print(list(only_in_last))
print("\nOnly in input_data:")
print(list(only_in_input))

Only in last_input_data:
[]

Only in input_data:
['ef_fgtv_distribution_tonne_ch4_per_m3_fuel_crude', 'ef_fgtv_distribution_tonne_co2_per_m3_fuel_crude', 'ef_fgtv_production_flaring_tonne_ch4_per_m3_fuel_crude', 'ef_fgtv_production_flaring_tonne_co2_per_m3_fuel_crude', 'ef_fgtv_production_flaring_tonne_n2o_per_m3_fuel_crude', 'ef_fgtv_production_flaring_tonne_nmvoc_per_m3_fuel_crude', 'ef_fgtv_production_fugitive_tonne_ch4_per_m3_fuel_crude', 'ef_fgtv_production_fugitive_tonne_co2_per_m3_fuel_crude', 'ef_fgtv_production_fugitive_tonne_n2o_per_m3_fuel_crude', 'ef_fgtv_production_fugitive_tonne_nmvoc_per_m3_fuel_crude', 'ef_fgtv_production_venting_tonne_ch4_per_m3_fuel_crude', 'ef_fgtv_production_venting_tonne_co2_per_m3_fuel_crude', 'ef_fgtv_production_venting_tonne_n2o_per_m3_fuel_crude', 'ef_fgtv_production_venting_tonne_nmvoc_per_m3_fuel_crude', 'ef_fgtv_transmission_tonne_ch4_per_m3_fuel_crude', 'ef_fgtv_transmission_tonne_co2_per_m3_fuel_crude', 'ef_fgtv_transmission_tonne_n2o_per_m3_fuel_crude', 'ef_fgtv_transmission_tonne_nmvoc_per_m3_fuel_crude', 'frac_fgtv_drained_and_waste_ch4_flared_fuel_crude']

In [9]:
only_in_input

Index(['ef_fgtv_distribution_tonne_ch4_per_m3_fuel_crude',
       'ef_fgtv_distribution_tonne_co2_per_m3_fuel_crude',
       'ef_fgtv_production_flaring_tonne_ch4_per_m3_fuel_crude',
       'ef_fgtv_production_flaring_tonne_co2_per_m3_fuel_crude',
       'ef_fgtv_production_flaring_tonne_n2o_per_m3_fuel_crude',
       'ef_fgtv_production_flaring_tonne_nmvoc_per_m3_fuel_crude',
       'ef_fgtv_production_fugitive_tonne_ch4_per_m3_fuel_crude',
       'ef_fgtv_production_fugitive_tonne_co2_per_m3_fuel_crude',
       'ef_fgtv_production_fugitive_tonne_n2o_per_m3_fuel_crude',
       'ef_fgtv_production_fugitive_tonne_nmvoc_per_m3_fuel_crude',
       'ef_fgtv_production_venting_tonne_ch4_per_m3_fuel_crude',
       'ef_fgtv_production_venting_tonne_co2_per_m3_fuel_crude',
       'ef_fgtv_production_venting_tonne_n2o_per_m3_fuel_crude',
       'ef_fgtv_production_venting_tonne_nmvoc_per_m3_fuel_crude',
       'ef_fgtv_transmission_tonne_ch4_per_m3_fuel_crude',
       'ef_fgtv_transmission_tonne_co2_per_m3_fuel_crude',
       'ef_fgtv_transmission_tonne_n2o_per_m3_fuel_crude',
       'ef_fgtv_transmission_tonne_nmvoc_per_m3_fuel_crude',
       'frac_fgtv_drained_and_waste_ch4_flared_fuel_crude'],
      dtype='object')