In [76]:
import copy
import datetime as dt
from datetime import datetime
import importlib  # needed so that we can reload packages
import logging
import os
import pathlib
import sys
import time
import warnings
from typing import Union, Tuple

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from utils.logger_utils import setup_clean_logger, mute_external_loggers

# SISEPUEDE imports
from sisepuede.manager.sisepuede_examples import SISEPUEDEExamples
from sisepuede.manager.sisepuede_file_structure import SISEPUEDEFileStructure
import sisepuede.core.support_classes as sc
import sisepuede.transformers as trf
import sisepuede.utilities._plotting as spu
import sisepuede.utilities._toolbox as sf
import sisepuede.core.attribute_table as att
import sisepuede.manager.sisepuede_examples as sxl
import sisepuede.manager.sisepuede_file_structure as sfs
import sisepuede.manager.sisepuede_models as sm
import sisepuede.visualization.plots as svp

# --- Runtime configuration ---
warnings.filterwarnings("ignore")

# Set up a clean logger for your notebook
logger = setup_clean_logger("notebook", logging.INFO)
logger.info("Notebook started successfully.")

# Mute logs from sisepuede to avoid duplication
mute_external_loggers(["sisepuede"])

2026-03-10 22:43:02,018 - INFO - Notebook started successfully.

In [77]:
from ssp_transformations_handler.GeneralUtils import GeneralUtils
from ssp_transformations_handler.TransformationUtils import TransformationYamlProcessor, StrategyCSVHandler

# Initialize general utilities
g_utils = GeneralUtils()

In [78]:
# Set up dir paths

CURR_DIR_PATH = pathlib.Path(os.getcwd())
SSP_MODELING_DIR_PATH = CURR_DIR_PATH.parent
PROJECT_DIR_PATH = SSP_MODELING_DIR_PATH.parent
DATA_DIR_PATH = SSP_MODELING_DIR_PATH.joinpath("input_data")
RUN_OUTPUT_DIR_PATH = SSP_MODELING_DIR_PATH.joinpath("ssp_run_output")
SCENARIO_MAPPING_DIR_PATH = SSP_MODELING_DIR_PATH.joinpath("scenario_mapping")
CONFIG_DIR_PATH = CURR_DIR_PATH.joinpath("config_files")
TRANSFORMATIONS_DIR_PATH = SSP_MODELING_DIR_PATH.joinpath("transformations")
MISC_DIR_PATH = SSP_MODELING_DIR_PATH.joinpath("misc")
STRATEGIES_DEFINITIONS_FILE_PATH = TRANSFORMATIONS_DIR_PATH.joinpath("strategy_definitions.csv")
STRATEGY_MAPPING_FILE_PATH = MISC_DIR_PATH.joinpath("strategy_mapping.yaml")

In [79]:
# Load config file, double check your parameters are correct

YAML_FILE_PATH = os.path.join(CONFIG_DIR_PATH, "config.yaml")
config_params = g_utils.read_yaml(YAML_FILE_PATH)

country_name = config_params['country_name']
ssp_input_file_name = config_params['ssp_input_file_name']
ssp_transformation_cw = config_params['ssp_transformation_cw']
energy_model_flag = config_params['energy_model_flag']
set_lndu_reallocation_factor_to_zero_flag = config_params['set_lndu_reallocation_factor_to_zero']
sim_end_year = config_params.get('sim_end_year', 2050)  # Default to 2050 if not specified

# Print config parameters
logger.info(f"Country name: {country_name}")
logger.info(f"SSP input file name: {ssp_input_file_name}")
logger.info(f"SSP transformation CW: {ssp_transformation_cw}")
logger.info(f"Energy model flag: {energy_model_flag}")
logger.info(f"Set lndu reallocation factor to zero flag: {set_lndu_reallocation_factor_to_zero_flag}")
logger.info(f"Simulation end year: {sim_end_year}")

2026-03-10 22:43:02,036 - INFO - Country name: libya
2026-03-10 22:43:02,037 - INFO - SSP input file name: ssp_libya_inputs_02032026.csv
2026-03-10 22:43:02,037 - INFO - SSP transformation CW: ssp_libya_transformation_cw_20260310.xlsx
2026-03-10 22:43:02,037 - INFO - Energy model flag: True
2026-03-10 22:43:02,038 - INFO - Set lndu reallocation factor to zero flag: True
2026-03-10 22:43:02,038 - INFO - Simulation end year: 2050

In [80]:
def get_file_structure(
    y0: int = 2015,
    y1: int = sim_end_year,
) -> Tuple[sfs.SISEPUEDEFileStructure, att.AttributeTable]:
    """Get the SISEPUEDE File Structure and update the attribute table
        with new years.
    """
    # setup some SISEPUEDE variables and update time period
    file_struct = sfs.SISEPUEDEFileStructure(
        initialize_directories = False,
    )
 
    # get some keys
    key_time_period = file_struct.model_attributes.dim_time_period
    key_year = file_struct.model_attributes.field_dim_year
 
 
    ##  BUILD THE ATTRIBUTE AND UPDATE
 
    # setup the new attribute table
    years = np.arange(y0, y1 + 1, ).astype(int)
    attribute_time_period = att.AttributeTable(
        pd.DataFrame(
            {
                key_time_period: range(len(years)),
                key_year: years,
            }
        ),
        key_time_period,
    )
 
    # finally, update the ModelAttributes inside the file structure
    (
        file_struct
        .model_attributes
        .update_dimensional_attribute_table(
            attribute_time_period,
        )
    )
 
    # return the tuple
    out = (file_struct, attribute_time_period, )
 
    return out

In [81]:
# Set up SSP objects
INPUT_FILE_PATH = DATA_DIR_PATH.joinpath(ssp_input_file_name)

# model attributes and associated support classes
_EXAMPLES = sxl.SISEPUEDEExamples()
_FILE_STRUCTURE, _ATTRIBUTE_TABLE_TIME_PERIOD = get_file_structure(y1=sim_end_year)
matt = _FILE_STRUCTURE.model_attributes
regions = sc.Regions(matt, )
time_periods = sc.TimePeriods(matt, )

In [82]:
path_transformations = pathlib.Path("/Users/fabianfuentes/git/ssp_libya/ssp_modeling/transformations")

##  --HERE, CUSTOMIZE YOUR TRANSFORMATIONS AND STRATEGIES--

### Customizing transformations and strategies files using TransformationUtils.py classes

In [83]:
# Generate new transformation files based on the excel mapping file. 
# Make sure to have the most updated format for the excel file, check the one used in this notebook for reference.

if ssp_transformation_cw is None:
    logger.warning("ssp_transformation_cw is not defined. Please check your config file.")
else:
    logger.info(f"Using transformation file: {ssp_transformation_cw}")
    cw_file_path = os.path.join(SCENARIO_MAPPING_DIR_PATH, ssp_transformation_cw)
    logger.info(f"Transformation file path: {cw_file_path}")
    excel_yaml_handler = TransformationYamlProcessor(scenario_mapping_excel_path=cw_file_path, yaml_dir_path=TRANSFORMATIONS_DIR_PATH)

2026-03-10 22:43:02,681 - INFO - Using transformation file: ssp_libya_transformation_cw_20260310.xlsx
2026-03-10 22:43:02,682 - INFO - Transformation file path: /Users/fabianfuentes/git/ssp_libya/ssp_modeling/scenario_mapping/ssp_libya_transformation_cw_20260310.xlsx

In [84]:
# This creates transformation yaml files for each strategy in the excel file
if ssp_transformation_cw is not None:
    logger.info("Processing YAML files...")
    excel_yaml_handler.process_yaml_files()
else:
    logger.warning("ssp_transformation_cw is not defined. Please check your config file.")

2026-03-10 22:43:02,782 - INFO - Processing YAML files...

==================================================
[transformation_entc_dec_losses.yaml | TX:ENTC:DEC_LOSSES] Reduce transmission losses (ENTC) | Start: 12
Strategy: strategy_NDC, Scalar value: 0.3
==================================================
==================================================
[transformation_entc_dec_losses.yaml | TX:ENTC:DEC_LOSSES] Reduce transmission losses (ENTC) | Start: 12
Strategy: strategy_LEP, Scalar value: 0.3
==================================================
==================================================
[transformation_entc_target_renewable_elec.yaml | TX:ENTC:TARGET_RENEWABLE_ELEC] 95% of electricity is generated by renewables in 2050 (ENTC) | Start: 12
Strategy: strategy_NDC, Scalar value: 0.3
==================================================
==================================================
[transformation_entc_target_renewable_elec.yaml | TX:ENTC:TARGET_RENEWABLE_ELEC] 95% of electricity is generated by renewables in 2050 (ENTC) | Start: 12
Strategy: strategy_LEP, Scalar value: 0.3
==================================================
==================================================
[transformation_fgtv_dec_leaks.yaml | TX:FGTV:DEC_LEAKS] Minimize leaks (FGTV) | Start: 12
Strategy: strategy_NDC, Scalar value: 0.15
==================================================
==================================================
[transformation_fgtv_dec_leaks.yaml | TX:FGTV:DEC_LEAKS] Minimize leaks (FGTV) | Start: 12
Strategy: strategy_LEP, Scalar value: 0.3
==================================================
==================================================
[transformation_fgtv_inc_flare.yaml | TX:FGTV:INC_FLARE] Maximize flaring (FGTV) | Start: 12
Strategy: strategy_NDC, Scalar value: 0.15
==================================================
==================================================
[transformation_fgtv_inc_flare.yaml | TX:FGTV:INC_FLARE] Maximize flaring (FGTV) | Start: 12
Strategy: strategy_LEP, Scalar value: 0.3
==================================================
==================================================
[transformation_inen_inc_efficiency_energy.yaml | TX:INEN:INC_EFFICIENCY_ENERGY] Maximize industrial energy efficiency (INEN) | Start: 12
Strategy: strategy_NDC, Scalar value: 0.3
==================================================
==================================================
[transformation_inen_inc_efficiency_energy.yaml | TX:INEN:INC_EFFICIENCY_ENERGY] Maximize industrial energy efficiency (INEN) | Start: 12
Strategy: strategy_LEP, Scalar value: 0.5
==================================================
==================================================
[transformation_inen_inc_efficiency_production.yaml | TX:INEN:INC_EFFICIENCY_PRODUCTION] Maximize industrial production efficiency (INEN) | Start: 12
Strategy: strategy_NDC, Scalar value: 0.3
==================================================
==================================================
[transformation_inen_inc_efficiency_production.yaml | TX:INEN:INC_EFFICIENCY_PRODUCTION] Maximize industrial production efficiency (INEN) | Start: 12
Strategy: strategy_LEP, Scalar value: 0.5
==================================================
==================================================
[transformation_inen_shift_fuel_heat.yaml | TX:INEN:SHIFT_FUEL_HEAT] Fuel switch high- and low-temp thermal processes.  (INEN) | Start: 12
Strategy: strategy_NDC, Scalar value: 0.3
YAML file transformation_inen_shift_fuel_heat.yaml already exists for strategy strategy_NDC. Please check manually.
==================================================
[transformation_inen_shift_fuel_heat.yaml | TX:INEN:SHIFT_FUEL_HEAT] Fuel switch high- and low-temp thermal processes.  (INEN) | Start: 12
Strategy: strategy_LEP, Scalar value: 0.5
YAML file transformation_inen_shift_fuel_heat.yaml already exists for strategy strategy_LEP. Please check manually.
==================================================
[transformation_ippu_dec_clinker.yaml | TX:IPPU:DEC_CLINKER] Reduce cement clinker (IPPU) | Start: 12
Strategy: strategy_NDC, Scalar value: 0.3
==================================================
==================================================
[transformation_ippu_dec_clinker.yaml | TX:IPPU:DEC_CLINKER] Reduce cement clinker (IPPU) | Start: 12
Strategy: strategy_LEP, Scalar value: 0.5
==================================================
==================================================
[transformation_ippu_dec_hfcs.yaml | TX:IPPU:DEC_HFCS] Reduce use of HFCs (IPPU) | Start: 12
Strategy: strategy_NDC, Scalar value: 0.3
==================================================
==================================================
[transformation_ippu_dec_hfcs.yaml | TX:IPPU:DEC_HFCS] Reduce use of HFCs (IPPU) | Start: 12
Strategy: strategy_LEP, Scalar value: 0.5
==================================================
==================================================
[transformation_lndu_inc_reforestation.yaml | TX:LNDU:INC_REFORESTATION] Increase Reforestation (LNDU) | Start: 12
Strategy: strategy_NDC, Scalar value: 0.3
==================================================
==================================================
[transformation_lndu_inc_reforestation.yaml | TX:LNDU:INC_REFORESTATION] Increase Reforestation (LNDU) | Start: 12
Strategy: strategy_LEP, Scalar value: 0.5
==================================================
==================================================
[transformation_lsmm_inc_management_cattle_pigs.yaml | TX:LSMM:INC_MANAGEMENT_CATTLE_PIGS] Improve manure management for cattle and pigs (LSMM) | Start: 12
Strategy: strategy_NDC, Scalar value: 0.3
YAML file transformation_lsmm_inc_management_cattle_pigs.yaml already exists for strategy strategy_NDC. Please check manually.
==================================================
[transformation_lsmm_inc_management_cattle_pigs.yaml | TX:LSMM:INC_MANAGEMENT_CATTLE_PIGS] Improve manure management for cattle and pigs (LSMM) | Start: 12
Strategy: strategy_LEP, Scalar value: 0.5
YAML file transformation_lsmm_inc_management_cattle_pigs.yaml already exists for strategy strategy_LEP. Please check manually.
==================================================
[transformation_lvst_dec_enteric_fermentation.yaml | TX:LVST:DEC_ENTERIC_FERMENTATION] Reduce enteric fermentation (LVST) | Start: 12
Strategy: strategy_NDC, Scalar value: 0.3
YAML file transformation_lvst_dec_enteric_fermentation.yaml already exists for strategy strategy_NDC. Please check manually.
==================================================
[transformation_lvst_dec_enteric_fermentation.yaml | TX:LVST:DEC_ENTERIC_FERMENTATION] Reduce enteric fermentation (LVST) | Start: 12
Strategy: strategy_LEP, Scalar value: 0.5
YAML file transformation_lvst_dec_enteric_fermentation.yaml already exists for strategy strategy_LEP. Please check manually.
==================================================
[transformation_scoe_dec_demand_heat.yaml | TX:SCOE:DEC_DEMAND_HEAT] Reduce end-use demand for heat energy by improving building shell (SCOE) | Start: 12
Strategy: strategy_NDC, Scalar value: 0.2
==================================================
==================================================
[transformation_scoe_dec_demand_heat.yaml | TX:SCOE:DEC_DEMAND_HEAT] Reduce end-use demand for heat energy by improving building shell (SCOE) | Start: 12
Strategy: strategy_LEP, Scalar value: 0.5
==================================================
==================================================
[transformation_scoe_inc_efficiency_appliance.yaml | TX:SCOE:INC_EFFICIENCY_APPLIANCE] Increase appliance efficiency (SCOE) | Start: 12
Strategy: strategy_NDC, Scalar value: 0.3
==================================================
==================================================
[transformation_scoe_inc_efficiency_appliance.yaml | TX:SCOE:INC_EFFICIENCY_APPLIANCE] Increase appliance efficiency (SCOE) | Start: 12
Strategy: strategy_LEP, Scalar value: 0.5
==================================================
==================================================
[transformation_scoe_shift_fuel_heat.yaml | TX:SCOE:SHIFT_FUEL_HEAT] Switch to electricity for heat using heat pumps, electric stoves, etc. (SCOE) | Start: 12
Strategy: strategy_NDC, Scalar value: 0.2
==================================================
==================================================
[transformation_scoe_shift_fuel_heat.yaml | TX:SCOE:SHIFT_FUEL_HEAT] Switch to electricity for heat using heat pumps, electric stoves, etc. (SCOE) | Start: 12
Strategy: strategy_LEP, Scalar value: 0.4
==================================================
==================================================
[transformation_soil_dec_n_applied.yaml | TX:SOIL:DEC_N_APPLIED] Improve fertilizer application (SOIL) | Start: 12
Strategy: strategy_NDC, Scalar value: 0.3
==================================================
==================================================
[transformation_soil_dec_n_applied.yaml | TX:SOIL:DEC_N_APPLIED] Improve fertilizer application (SOIL) | Start: 12
Strategy: strategy_LEP, Scalar value: 0.5
==================================================
==================================================
[transformation_trde_dec_demand.yaml | TX:TRDE:DEC_DEMAND] Reduce demand for transport (TRDE) | Start: 12
Strategy: strategy_NDC, Scalar value: 0.3
==================================================
==================================================
[transformation_trde_dec_demand.yaml | TX:TRDE:DEC_DEMAND] Reduce demand for transport (TRDE) | Start: 12
Strategy: strategy_LEP, Scalar value: 0.5
==================================================
==================================================
[transformation_trns_inc_efficiency_electric.yaml | TX:TRNS:INC_EFFICIENCY_ELECTRIC] Increase electric transportation energy efficiency (TRNS) | Start: 12
Strategy: strategy_NDC, Scalar value: 0.3
==================================================
==================================================
[transformation_trns_inc_efficiency_electric.yaml | TX:TRNS:INC_EFFICIENCY_ELECTRIC] Increase electric transportation energy efficiency (TRNS) | Start: 12
Strategy: strategy_LEP, Scalar value: 0.5
==================================================
==================================================
[transformation_trns_shift_fuel_light_duty.yaml | TX:TRNS:SHIFT_FUEL_LIGHT_DUTY] Electrify light duty road transport (TRNS) | Start: 12
Strategy: strategy_NDC, Scalar value: 0.2
==================================================
==================================================
[transformation_trns_shift_fuel_light_duty.yaml | TX:TRNS:SHIFT_FUEL_LIGHT_DUTY] Electrify light duty road transport (TRNS) | Start: 12
Strategy: strategy_LEP, Scalar value: 0.4
==================================================
==================================================
[transformation_trns_shift_fuel_medium_duty.yaml | TX:TRNS:SHIFT_FUEL_MEDIUM_DUTY] Fuel switch medium duty road transport (TRNS) | Start: 12
Strategy: strategy_NDC, Scalar value: 0.2
==================================================
==================================================
[transformation_trns_shift_fuel_medium_duty.yaml | TX:TRNS:SHIFT_FUEL_MEDIUM_DUTY] Fuel switch medium duty road transport (TRNS) | Start: 12
Strategy: strategy_LEP, Scalar value: 0.4
==================================================
==================================================
[transformation_trns_shift_mode_passenger.yaml | TX:TRNS:SHIFT_MODE_PASSENGER] Mode shift passenger vehicles to others (TRNS) | Start: 12
Strategy: strategy_NDC, Scalar value: 0.3
==================================================
==================================================
[transformation_trns_shift_mode_passenger.yaml | TX:TRNS:SHIFT_MODE_PASSENGER] Mode shift passenger vehicles to others (TRNS) | Start: 12
Strategy: strategy_LEP, Scalar value: 0.5
==================================================
==================================================
[transformation_trww_inc_capture_biogas.yaml | TX:TRWW:INC_CAPTURE_BIOGAS] Increase biogas capture (TRWW) | Start: 12
Strategy: strategy_NDC, Scalar value: 0.2
==================================================
==================================================
[transformation_trww_inc_capture_biogas.yaml | TX:TRWW:INC_CAPTURE_BIOGAS] Increase biogas capture (TRWW) | Start: 12
Strategy: strategy_LEP, Scalar value: 0.4
==================================================
==================================================
[transformation_wali_inc_treatment_urban.yaml | TX:WALI:INC_TREATMENT_URBAN] Improved urban wastewater treatment (WALI) | Start: 12
Strategy: strategy_NDC, Scalar value: 0.3
YAML file transformation_wali_inc_treatment_urban.yaml already exists for strategy strategy_NDC. Please check manually.
==================================================
[transformation_wali_inc_treatment_urban.yaml | TX:WALI:INC_TREATMENT_URBAN] Improved urban wastewater treatment (WALI) | Start: 12
Strategy: strategy_LEP, Scalar value: 0.5
YAML file transformation_wali_inc_treatment_urban.yaml already exists for strategy strategy_LEP. Please check manually.
==================================================
[transformation_waso_dec_consumer_food_waste.yaml | TX:WASO:DEC_CONSUMER_FOOD_WASTE] Consumer food waste reduction (WASO) | Start: 12
Strategy: strategy_NDC, Scalar value: 0.3
==================================================
==================================================
[transformation_waso_dec_consumer_food_waste.yaml | TX:WASO:DEC_CONSUMER_FOOD_WASTE] Consumer food waste reduction (WASO) | Start: 12
Strategy: strategy_LEP, Scalar value: 0.5
==================================================
==================================================
[transformation_waso_inc_anaerobic_and_compost.yaml | TX:WASO:INC_ANAEROBIC_AND_COMPOST] Increase composting and biogas (WASO) | Start: 12
Strategy: strategy_NDC, Scalar value: 0.3
YAML file transformation_waso_inc_anaerobic_and_compost.yaml already exists for strategy strategy_NDC. Please check manually.
==================================================
[transformation_waso_inc_anaerobic_and_compost.yaml | TX:WASO:INC_ANAEROBIC_AND_COMPOST] Increase composting and biogas (WASO) | Start: 12
Strategy: strategy_LEP, Scalar value: 0.5
YAML file transformation_waso_inc_anaerobic_and_compost.yaml already exists for strategy strategy_LEP. Please check manually.
==================================================
[transformation_waso_inc_capture_biogas.yaml | TX:WASO:INC_CAPTURE_BIOGAS] Increase biogas capture (WASO) | Start: 12
Strategy: strategy_NDC, Scalar value: 0.2
==================================================
==================================================
[transformation_waso_inc_capture_biogas.yaml | TX:WASO:INC_CAPTURE_BIOGAS] Increase biogas capture (WASO) | Start: 12
Strategy: strategy_LEP, Scalar value: 0.4
==================================================
==================================================
[transformation_waso_inc_energy_from_biogas.yaml | TX:WASO:INC_ENERGY_FROM_BIOGAS] Biogas for energy production (WASO) | Start: 12
Strategy: strategy_NDC, Scalar value: 0.2
==================================================
==================================================
[transformation_waso_inc_energy_from_biogas.yaml | TX:WASO:INC_ENERGY_FROM_BIOGAS] Biogas for energy production (WASO) | Start: 12
Strategy: strategy_LEP, Scalar value: 0.4
==================================================
==================================================
[transformation_waso_inc_energy_from_incineration.yaml | TX:WASO:INC_ENERGY_FROM_INCINERATION] Incineration for energy production (WASO) | Start: 12
Strategy: strategy_NDC, Scalar value: 0.2
==================================================
==================================================
[transformation_waso_inc_energy_from_incineration.yaml | TX:WASO:INC_ENERGY_FROM_INCINERATION] Incineration for energy production (WASO) | Start: 12
Strategy: strategy_LEP, Scalar value: 0.4
==================================================

In [85]:
# Load the transformations per strategy dictionary so we can pass it to the strategy handler
# You can also check here if the transformations in each strategy are correct

if ssp_transformation_cw is not None:
    logger.info("Loading transformations per strategy dictionary...")
    transformation_per_strategy_dict = excel_yaml_handler.get_transformations_per_strategy_dict()
    transformation_per_strategy_dict
    logger.info(f"Loaded transformations for strategies: {transformation_per_strategy_dict.keys()}")
else:
    logger.warning("No transformation handler available. Please check your config file.")

2026-03-10 22:43:02,824 - INFO - Loading transformations per strategy dictionary...
2026-03-10 22:43:02,826 - INFO - Loaded transformations for strategies: dict_keys(['strategy_NDC', 'strategy_LEP'])

### Creating new strategies
- You can create new strategies from scratch.
- You can also update existing ones.

In [86]:
# Creating new strategies by updating the strategy_definitions file.

if ssp_transformation_cw is not None:
    # You can edit this to add yours, as many as you want.
    csv_handler = StrategyCSVHandler(csv_file_path=STRATEGIES_DEFINITIONS_FILE_PATH, 
                                     yaml_dir_path=TRANSFORMATIONS_DIR_PATH, 
                                     yaml_mapping_file=STRATEGY_MAPPING_FILE_PATH, 
                                     transformation_per_strategy_dict=transformation_per_strategy_dict)
    csv_handler.add_strategy(strategy_group='PFLO', description='NDC', yaml_file_suffix='NDC')
    csv_handler.add_strategy(strategy_group='PFLO', description='LEP', yaml_file_suffix='LEP')
else:
    logger.warning("No transformation handler available. Please check your config file.")

INFO: Strategy code PFLO:NDC already exists in the strategy definitions. Strategy will be updated...
Updated row with strategy_code PFLO:NDC
INFO: Strategy code PFLO:LEP already exists in the strategy definitions. Strategy will be updated...
Updated row with strategy_code PFLO:LEP

**Manual tunning of some yamls**

In [87]:
# Temporary fix to add a parameter to the yaml files
from ruamel.yaml import YAML
yaml = YAML()
# tell it to keep your original quoting
yaml.preserve_quotes = True

def add_parameter_to_yaml_file(yaml_file_path, parameter_key, parameter_value):
   
    with open(yaml_file_path, 'r') as f:
        data = yaml.load(f)              # <-- ruamel.yaml keeps your formatting

        if 'parameters' not in data:
            raise ValueError(f"{yaml_file_path!r} has no ‘parameters’ key")
        
        data['parameters'][parameter_key] = parameter_value  # add your key

        with open(yaml_file_path, 'w') as f:
            yaml.dump(data, f)               # <-- dumps with the *same* quotes, indents, folds

In [88]:
increase_exports_path_ndc = os.path.join(TRANSFORMATIONS_DIR_PATH, "transformation_enfu_adj_exports_strategy_NDC.yaml")
increase_exports_path_lep = os.path.join(TRANSFORMATIONS_DIR_PATH, "transformation_enfu_adj_exports_strategy_LEP.yaml")
target_renewables_ndc = os.path.join(TRANSFORMATIONS_DIR_PATH, "transformation_entc_target_renewable_elec_strategy_NDC.yaml")
target_renewables_lep = os.path.join(TRANSFORMATIONS_DIR_PATH, "transformation_entc_target_renewable_elec_strategy_LEP.yaml")

In [89]:
add_parameter_to_yaml_file(
    increase_exports_path_ndc,
    "cats_enfu",
    ["fuel_natural_gas"]
)

add_parameter_to_yaml_file(
    increase_exports_path_lep,
    "cats_enfu",
    ["fuel_natural_gas"]
)

# add_parameter_to_yaml_file(
#     target_renewables_ndc,
#     "dict_entc_renewable_target_msp",
#     {
#     # "pp_gas_ccs": 0.64,
#     "pp_wind": 0.10,
#     "pp_geothermal": 0.05,
#     "pp_solar": 0.35
#     }
# )

# add_parameter_to_yaml_file(
#     target_renewables_ndc,
#     "scale_non_renewables_to_match_surplus_msp",True
# )

# add_parameter_to_yaml_file(
#     target_renewables_lep,
#     "dict_entc_renewable_target_msp",
#     {
#     # "pp_solar": 0.20,
#     # "pp_gas_ccs": 0.64,
#     "pp_wind": 0.10,
#     "pp_geothermal": 0.10
#     }
# )

In [90]:
df_inputs_raw = pd.read_csv(INPUT_FILE_PATH)

In [91]:
INPUT_FILE_PATH

PosixPath('/Users/fabianfuentes/git/ssp_libya/ssp_modeling/input_data/ssp_libya_inputs_02032026.csv')

In [92]:
# Set region to country name
df_inputs_raw['region'] = country_name
df_inputs_raw['region'].head()

0    libya
1    libya
2    libya
3    libya
4    libya
Name: region, dtype: object

In [93]:
df_inputs_raw.head()

,year,ef_ippu_tonne_nf3_per_tonne_production_chemicals,ef_ippu_tonne_nf3_per_tonne_production_electronics,ef_ippu_tonne_sf6_per_mmm_gdp_other_product_manufacturing,ef_ippu_tonne_sf6_per_tonne_production_chemicals,ef_ippu_tonne_sf6_per_tonne_production_electronics,ef_ippu_tonne_sf6_per_tonne_production_metals,frac_agrc_bevs_and_spices_cl2_dry,frac_agrc_cereals_cl2_dry,frac_agrc_fibers_cl2_dry,...,nemomod_entc_scalar_availability_factor_pp_geothermal,nemomod_entc_scalar_availability_factor_pp_hydropower,nemomod_entc_scalar_availability_factor_pp_nuclear,nemomod_entc_scalar_availability_factor_pp_ocean,nemomod_entc_scalar_availability_factor_pp_oil,nemomod_entc_scalar_availability_factor_pp_solar,nemomod_entc_scalar_availability_factor_pp_waste_incineration,nemomod_entc_scalar_availability_factor_pp_wind,iso_alpha_3,region
0,2015,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,...,1.0,0,0.0,1.0,1.0,1.0,1.0,1.0,LBY,libya
1,2016,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,...,1.0,0,0.0,1.0,1.0,1.0,1.0,1.0,LBY,libya
2,2017,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,...,1.0,0,0.0,1.0,1.0,1.0,1.0,1.0,LBY,libya
3,2018,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,...,1.0,0,0.0,1.0,1.0,1.0,1.0,1.0,LBY,libya
4,2019,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,...,1.0,0,0.0,1.0,1.0,1.0,1.0,1.0,LBY,libya

In [94]:
import sisepuede.transformers as trf
import sisepuede.transformers.transformations as tmts
importlib.reload(tmts.trs)


transformers = trf.Transformers(
    {},
    df_input = df_inputs_raw,
)


# initialize a transformations set
if not path_transformations.is_dir():
    trf.instantiate_default_strategy_directory(
        transformers,
        path_transformations,
    )

In [95]:
transformations = tmts.Transformations(
    path_transformations,
    df_input = df_inputs_raw,
)

In [96]:
transformers = transformations.transformers

strategies = trf.Strategies(
    transformations,
    export_path = "transformations",
    prebuild = True,
)

In [ ]:

attribute_strategy_new = sf._concat_df(
    [
        strategies.attribute_table.table,
        strategies.build_whirlpool_strategies(6004, )
    ]
)

attribute_strategy_new

,strategy_id,strategy_code,strategy,description,transformation_specification,baseline_strategy_id
0,0,BASE,Strategy TX:BASE,NaN,TX:BASE,1.0
1,1000,AGRC:DEC_CH4_RICE,Singleton - Default Value - AGRC: Improve rice...,NaN,TX:AGRC:DEC_CH4_RICE,0.0
2,1001,AGRC:DEC_EXPORTS,Singleton - Default Value - AGRC: Decrease Exp...,NaN,TX:AGRC:DEC_EXPORTS,0.0
3,1002,AGRC:DEC_LOSSES_SUPPLY_CHAIN,Singleton - Default Value - AGRC: Reduce suppl...,NaN,TX:AGRC:DEC_LOSSES_SUPPLY_CHAIN,0.0
4,1003,AGRC:INC_CONSERVATION_AGRICULTURE,Singleton - Default Value - AGRC: Expand conse...,NaN,TX:AGRC:INC_CONSERVATION_AGRICULTURE,0.0
...,...,...,...,...,...,...
99,6028,WHIRLPOOL:TX:WASO:DEC_CONSUMER_FOOD_WASTE_STRA...,Remove TX:WASO:DEC_CONSUMER_FOOD_WASTE_STRATEG...,,TX:ENTC:DEC_LOSSES_STRATEGY_LEP|TX:ENTC:TARGET...,0.0
100,6029,WHIRLPOOL:TX:WASO:INC_ANAEROBIC_AND_COMPOST_ST...,Remove TX:WASO:INC_ANAEROBIC_AND_COMPOST_STRAT...,,TX:ENTC:DEC_LOSSES_STRATEGY_LEP|TX:ENTC:TARGET...,0.0
101,6030,WHIRLPOOL:TX:WASO:INC_CAPTURE_BIOGAS_STRATEGY_LEP,Remove TX:WASO:INC_CAPTURE_BIOGAS_STRATEGY_LEP...,,TX:ENTC:DEC_LOSSES_STRATEGY_LEP|TX:ENTC:TARGET...,0.0
102,6031,WHIRLPOOL:TX:WASO:INC_ENERGY_FROM_BIOGAS_STRAT...,Remove TX:WASO:INC_ENERGY_FROM_BIOGAS_STRATEGY...,,TX:ENTC:DEC_LOSSES_STRATEGY_LEP|TX:ENTC:TARGET...,0.0
103,6032,WHIRLPOOL:TX:WASO:INC_ENERGY_FROM_INCINERATION...,Remove TX:WASO:INC_ENERGY_FROM_INCINERATION_ST...,,TX:ENTC:DEC_LOSSES_STRATEGY_LEP|TX:ENTC:TARGET...,0.0

In [98]:
attribute_strategy_new.to_csv(
    path_transformations.joinpath("strategy_definition_whirlpool.csv"),
    encoding = "UTF-8",
    index = None
)

In [99]:
matt.get_dimensional_attribute_table(matt.dim_time_period).table

    time_period  year
0             0  2015
1             1  2016
2             2  2017
3             3  2018
4             4  2019
5             5  2020
6             6  2021
7             7  2022
8             8  2023
9             9  2024
10           10  2025
11           11  2026
12           12  2027
13           13  2028
14           14  2029
15           15  2030
16           16  2031
17           17  2032
18           18  2033
19           19  2034
20           20  2035
21           21  2036
22           22  2037
23           23  2038
24           24  2039
25           25  2040
26           26  2041
27           27  2042
28           28  2043
29           29  2044
30           30  2045
31           31  2046
32           32  2047
33           33  2048
34           34  2049
35           35  2050

In [100]:

##  WRITE SOME OBJECTS FOR USE WITH CLOUD

sf._write_csv(
    matt.get_dimensional_attribute_table(matt.dim_time_period).table,
    path_transformations.joinpath("attribute_dim_time_period.csv")
)

True

In [101]:
strategies.get_strategy(6004).code

'PFLO:LEP'